### ISSUE TITLE
Missing log directory causes a panic

### ISSUE THREAD

**Issue by ioerror** [katzenpost/katzenpost#119]
Having a configured log directory (do we need logs at all? I don't think so...) that is missing causes a crash:
```
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: 20:16:32.021 DEBU client: plugin socket path:'Log directory '/var/log/katzenpost' doesn't exist.'
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: 20:16:32.021 DEBU client_socket: dialing unix domain socket file: Log directory '/var/log/katzenpost' doesn't exist.
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: 20:16:32.021 NOTI server: Starting graceful shutdown.
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: 20:16:32.022 ERRO client: CBOR plugin worker, command exec error: exit status 1
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: 20:16:32.030 NOTI server: Shutdown complete.
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: panic: dial unix Log directory '/var/log/katzenpost' doesn't exist.: connect: no such file or directory
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: goroutine 1 [running]:
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: github.com/katzenpost/katzenpost/server/cborplugin.(*CommandIO).Start(0xc0002fe300, 0x70?, {0xc0005c8040?, 0xc0002fe280?}, {0x10617b58?, 0x109795c0?})
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]:         /home/user/katzenpost/server/cborplugin/socket.go:74 +0x294
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: github.com/katzenpost/katzenpost/server/cborplugin.(*Client).Start(0xc0002a8320, {0xc0002bc2e0?, 0x5?}, {0xc0002fe280?, 0x6?, 0x10617b58?})
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]:         /home/user/katzenpost/server/cborplugin/client.go:176 +0xf0
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.(*CBORPluginWorker).launch(0xc0002ac870, {0xc0002bc2e0, 0x17}, {0xc000290408, 0x5}, {0xc000290440, 0x6}, {0xc0002fe280, 0x6, 0x8})
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]:         /home/user/katzenpost/server/internal/provider/kaetzchen/cbor_plugins.go:199 +0x168
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: github.com/katzenpost/katzenpost/server/internal/provider/kaetzchen.NewCBORPluginWorker({0x1061eb08, 0xc000010530})
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]:         /home/user/katzenpost/server/internal/provider/kaetzchen/cbor_plugins.go:259 +0x638
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: github.com/katzenpost/katzenpost/server/internal/provider.New({0x1061eb08?, 0xc000010530})
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]:         /home/user/katzenpost/server/internal/provider/provider.go:594 +0x74
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: github.com/katzenpost/katzenpost/server.New(0xc00028e5d0)
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]:         /home/user/katzenpost/server/server.go:387 +0xe70
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]: main.main()
Dec 08 20:16:32 power9 pq-katzenpost-mixserver[1092407]:         /home/user/katzenpost/server/cmd/server/main.go:66 +0x2d0
```

To fix this issue and allow the mix to start, I added a log directory:
```
systemctl stop pq-katzenpost-mixserver
mkdir /var/log/katzenpost
chown pq-katzenpost-mixserver:pq-katzenpost-mixserver /var/log/katzenpost
systemctl start pq-katzenpost-mixserver
```

**Comment by mixmasala** [comment]
The log directory you specified for your mixnet services is set by field log_dir, you should ensure that the path exists on your filesystem or else the mixserver crashes. It may be an improvment to log an error and graceful shutdown, but the mix service should not start with a misconfiguration.
