### ISSUE TITLE
Creation of contact without an established spool triggers panic

### ISSUE THREAD

**Issue by willscott** [katzenpost/katzenpost#164]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x8 pc=0x104a57cec]

goroutine 482 [running]:
github.com/katzenpost/katzenpost/memspool/client.(*SpoolReadDescriptor).GetWriteDescriptor(...)
	github.com/katzenpost/katzenpost@v0.0.17/memspool/client/client.go:66
github.com/katzenpost/katzenpost/catshadow.(*Client).initKeyExchange(0x1400017a500, 0x1403aec8000)
	github.com/katzenpost/katzenpost@v0.0.17/catshadow/client.go:231 +0x5c
github.com/katzenpost/katzenpost/catshadow.(*Client).createContact(0x1400017a500, {0x140503cb630, 0x4}, {0x140503cb640, 0xb, 0x10})
	github.com/katzenpost/katzenpost@v0.0.17/catshadow/client.go:470 +0x194
```

**Comment by leif** [comment]
Either something changed in the days since this happened, or this bug does not always occur: today I watched someone add a katzen contact with a new state file, prior to having ever connected. When they subsequently connected, their spool was created and then the key exchange completed successfully. I think maybe the difference is that in this ticket's crash there was a successful network connection prior to adding a contact.
