### ISSUE TITLE
invalid memory address or nil pointer dereference in sweepSURBCtxs on mix server

### ISSUE THREAD

**Issue by leif** [katzenpost/katzenpost#165]
```
panic: BUG: SURB mismatch in node ETA list

goroutine 32 [running]:
github.com/katzenpost/katzenpost/server/internal/decoy.(*decoy).loadAndDeleteSURBCtx(0xc0000b4000, 0x5?)
        /home/katzenpost/katzenpost/server/internal/decoy/decoy.go:408 +0x251
github.com/katzenpost/katzenpost/server/internal/decoy.(*decoy).OnPacket(0xc0000b4000, 0xc00ce7ea00)
        /home/katzenpost/katzenpost/server/internal/decoy/decoy.go:110 +0x279
github.com/katzenpost/katzenpost/server/internal/cryptoworker.(*Worker).worker(0xc000126380)
        /home/katzenpost/katzenpost/server/internal/cryptoworker/crypto_worker.go:271 +0xead
github.com/katzenpost/katzenpost/core/worker.(*Worker).Go.func1()
        /home/katzenpost/katzenpost/core/worker/worker.go:39 +0x5a
created by github.com/katzenpost/katzenpost/core/worker.(*Worker).Go
        /home/katzenpost/katzenpost/core/worker/worker.go:37 +0xb9
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x852596]

goroutine 43 [running]:
github.com/katzenpost/katzenpost/server/internal/decoy.(*decoy).sweepSURBCtxs(0xc000000280)
        /home/katzenpost/katzenpost/server/internal/decoy/decoy.go:440 +0x2b6
github.com/katzenpost/katzenpost/server/internal/decoy.(*decoy).worker(0xc000000280)
        /home/katzenpost/katzenpost/server/internal/decoy/decoy.go:190 +0x53a
github.com/katzenpost/katzenpost/core/worker.(*Worker).Go.func1()
        /home/katzenpost/katzenpost/core/worker/worker.go:39 +0x5a
created by github.com/katzenpost/katzenpost/core/worker.(*Worker).Go
        /home/katzenpost/katzenpost/core/worker/worker.go:37 +0xb9

```

**Comment by leif** [comment]
oops, i guess this is actually a duplicate of #133, which is apparently fixed by #136 (but v0.0.17 got tagged right before that landed).
