### ISSUE TITLE
decoy.go:465 panic: interface conversion: interface {} is *decoy.surbCtx, not []*decoy.surbCtx

### ISSUE THREAD

**Issue by leif** [katzenpost/katzenpost#208]
```
panic: interface conversion: interface {} is *decoy.surbCtx, not []*decoy.surbCtx

goroutine 41 [running]:
github.com/katzenpost/katzenpost/server/internal/decoy.New.func1({0x936f40?, 0xc00afb9bd8?}, {0x92fc20?, 0x0?})
        /home/katzenpost/katzenpost/server/internal/decoy/decoy.go:465 +0xc5
gitlab.com/yawning/avl%2egit.(*Tree).Insert(0xc0000126c0, {0x936f40?, 0xc00afb9bd8})
        /go/pkg/mod/gitlab.com/yawning/avl.git@v0.0.0-20180224045358-04c7c776e391/avl.go:211 +0x87
github.com/katzenpost/katzenpost/server/internal/decoy.(*decoy).storeSURBCtx(0xc0000003c0, 0xc00b1af740)
        /home/katzenpost/katzenpost/server/internal/decoy/decoy.go:369 +0xe8
github.com/katzenpost/katzenpost/server/internal/decoy.(*decoy).sendLoopPacket(0xc0000003c0, 0xc0070ef5e8?, {0xc0001c5de8, 0x5, 0x20}, 0xe0bf00?, 0x46976455c6?)
        /home/katzenpost/katzenpost/server/internal/decoy/decoy.go:283 +0x57b
github.com/katzenpost/katzenpost/server/internal/decoy.(*decoy).sendDecoyPacket(0xc0000003c0, 0xc0001c5ebc?)
        /home/katzenpost/katzenpost/server/internal/decoy/decoy.go:238 +0x1cd
github.com/katzenpost/katzenpost/server/internal/decoy.(*decoy).worker(0xc0000003c0)
        /home/katzenpost/katzenpost/server/internal/decoy/decoy.go:173 +0x405
github.com/katzenpost/katzenpost/core/worker.(*Worker).Go.func1()
        /home/katzenpost/katzenpost/core/worker/worker.go:39 +0x5a
created by github.com/katzenpost/katzenpost/core/worker.(*Worker).Go
        /home/katzenpost/katzenpost/core/worker/worker.go:37 +0xb9
```

**Comment by leif** [comment]
(this is related to #133 and #207)
