### ISSUE TITLE
dirauth crashes

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#302]
```

16:50:04.147 DEBU state: authority: Wakeup due to voting schedule.  
16:50:04.147 DEBU state: Current epoch 157076, remaining time:  
9m55.85207652s  
panic: runtime error: invalid memory address or nil pointer dereference  
\[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x68556a\]  
  
goroutine 14 \[running\]:  
[github.com/katzenpost/katzenpost/authority/voting/server.(\*state).getDocument(0xc000002140](http://github.com/katzenpost/katzenpost/authority/voting/server.(*state).getDocument(0xc000002140),  
{0x0, 0x0, 0xc0019936e0?}, 0x0, {0xc003fbd4e0, 0x20, 0x20})  
  
/home/katzenpost/katzenpost/authority/voting/server/state.go:516 +0x38a  
[github.com/katzenpost/katzenpost/authority/voting/server.(\*state).getMyConsensus(0xc000002140](http://github.com/katzenpost/katzenpost/authority/voting/server.(*state).getMyConsensus(0xc000002140),  
0x26595)  
  
/home/katzenpost/katzenpost/authority/voting/server/state.go:418 +0x3fe  
[github.com/katzenpost/katzenpost/authority/voting/server.(\*state).fsm(0xc000002140)](http://github.com/katzenpost/katzenpost/authority/voting/server.(*state).fsm(0xc000002140))  
  
/home/katzenpost/katzenpost/authority/voting/server/state.go:221 +0x19b  
[github.com/katzenpost/katzenpost/authority/voting/server.(\*state).worker(0xc000002140)](http://github.com/katzenpost/katzenpost/authority/voting/server.(*state).worker(0xc000002140))  
  
/home/katzenpost/katzenpost/authority/voting/server/state.go:149 +0x9f  
[github.com/katzenpost/katzenpost/core/worker.(\*Worker).Go.func1()](http://github.com/katzenpost/katzenpost/core/worker.(*Worker).Go.func1())  
         /home/katzenpost/katzenpost/core/worker/worker.go:39 +0x5a  
created by [github.com/katzenpost/katzenpost/core/worker.(\*Worker).Go](http://github.com/katzenpost/katzenpost/core/worker.(*Worker).Go)  
         /home/katzenpost/katzenpost/core/worker/worker.go:37 +0xb9
```

**Comment by threebithacker** [comment]
Primer on Go crash messages
```
panic: runtime error: invalid memory address or nil pointer dereference
  ^--
```
a pointer pointed to memory that wasn't mapped. unless something got corrupted, this is usually always a `nil`  pointer in Go
                                                                  
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x68556a]
            ^--- seg)mentation v)iolation
```
ancient language for "couldn't do the thing in ram you wanted"
```
                                           ^-- code 0x1 is the access mode mask.
```
0x1 is "read", so it's when the instruction tried to read data from the bad address.
```
                                                    ^-- addr=0x0 means it *was* a `nil` pointer
```
    pc=0x68556a: program counter, aka instruction pointer, this is the address of the machine code instruction that caused the access. the address is the *loaded* address (in memory), not in the ELF archive. in this case we are running without ASLR, so it's probably always the same (not great, but great for debugging). that's useful if you're using `gdb` for example.

```
 goroutine 35 [running]:                                                                                                 
           ^-- thread 35 I guess, this is also mainly useful if you're using `gdb` to debug it
                ^-- thread state. probably always `running` unless the bug is in the go runtime.
```

```                                                                                                                     
github.com/katzenpost/katzenpost/authority/voting/server.(*state).getDocument(0xc0002f2000, {0x0, 0x0, 0xc002e7fec0?},   
0x0, {0xc001dcb500, 0x20, 0x20})                                                                                         
   ^--
```
this is the function in which the code at pc=0x68556a resides, ie `katzenpost/authority/voting/server/state.go:func`
```
getDocument                                                                                                              
   the numbers are the arguments to the function:                                                                        
   func (s *state == 0xc0002f2000)                                                                                       
   getDocument(descriptors []*pki.MixDescriptor == {0x0, 0x0, 0xc002e7fec0?},                                            
               params *config.Parameters == 0x0, // nil                                                                  
               srv []byte == {0xc001dcb500, 0x20, 0x20}                                                                  
   ) *pki.Document {                                                                                                     
                                                                                                                         
here's the line :516 where pc is, and 0x38a is the instruction offset from the function start (`pc - 0x38a` is where the 
function machine code starts)                                                                                            
/home/katzenpost/katzenpost/authority/voting/server/state.go:516 +0x38a                                                  
```
