### ISSUE TITLE
doubleratchet segmentation violation in ctidh1024

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/katzenpost#605]
```
--- PASS: Test_KeyExchange (6.76s)
=== RUN   Test_RealKeyExchange
--- PASS: Test_RealKeyExchange (12.90s)
=== RUN   Test_Serialization0
--- PASS: Test_Serialization0 (0.98s)
=== RUN   Test_Serialization1
--- PASS: Test_Serialization1 (7.61s)
=== RUN   Test_RatchetBackAndForth
--- PASS: Test_RatchetBackAndForth (17.84s)
=== RUN   Test_RatchetReordering
--- PASS: Test_RatchetReordering (17.47s)
=== RUN   Test_RatchetReorderAfterDHRatchet
--- PASS: Test_RatchetReorderAfterDHRatchet (14.07s)
=== RUN   Test_RatchetDroppedMessages
--- PASS: Test_RatchetDroppedMessages (12.95s)
=== RUN   Test_serialize_savedkeys
SIGSEGV: segmentation violation
PC=0x6f43d5 m=7 sigcode=2
signal arrived during cgo execution

goroutine 29 [syscall]:
runtime.cgocall(0x6df180, 0xc00005abe8)
	/usr/lib/go/src/runtime/cgocall.go:157 +0x4b fp=0xc00005abc0 sp=0xc00005ab88 pc=0x406a4b
codeberg.org/vula/highctidh/src/ctidh1024._Cfunc_csidh(0xc0000fa200, 0xc0000fa180, 0xc0000ea360)
	_cgo_gotypes.go:98 +0x48 fp=0xc00005abe8 sp=0xc00005abc0 pc=0x567ba8
codeberg.org/vula/highctidh/src/ctidh1024.GroupAction(...)
	/root/go/pkg/mod/codeberg.org/vula/highctidh@v1.0.2024050500/src/ctidh1024/ctidh1024.go:260
codeberg.org/vula/highctidh/src/ctidh1024.DerivePublicKey(0xc0000ea360)
	/root/go/pkg/mod/codeberg.org/vula/highctidh@v1.0.2024050500/src/ctidh1024/ctidh1024.go:230 +0xac fp=0xc00005aca8 sp=0xc00005abe8 pc=0x5685cc
codeberg.org/vula/highctidh/src/ctidh1024.GenerateKeyPairWithRNG({0x9dbce0?, 0xc00014a080?})
	/root/go/pkg/mod/codeberg.org/vula/highctidh@v1.0.2024050500/src/ctidh1024/ctidh1024.go:255 +0x27 fp=0xc00005acd0 sp=0xc00005aca8 pc=0x568787
github.com/katzenpost/hpqc/nike/ctidh/ctidh1024.(*scheme).GenerateKeyPairFromEntropy(0xc000102400?, {0x9dbce0?, 0xc00014a080?})
	/root/go/pkg/mod/github.com/katzenpost/hpqc@v0.0.31/nike/ctidh/ctidh1024/ctidh.go:70 +0x27 fp=0xc00005ad08 sp=0xc00005acd0 pc=0x568e27
github.com/katzenpost/hpqc/nike/hybrid.(*Scheme).GenerateKeyPairFromEntropy(0xbaf580, {0x9dbce0, 0xc00014a080})
	/root/go/pkg/mod/github.com/katzenpost/hpqc@v0.0.31/nike/hybrid/hybrid.go:77 +0x35 fp=0xc00005ad78 sp=0xc00005ad08 pc=0x5a30f5
github.com/katzenpost/katzenpost/doubleratchet.InitRatchet({0x9dbce0?, 0xc00014a080}, {0x9e0320, 0xbaf580})
	/build/katzenpost/doubleratchet/ratchet.go:385 +0x110 fp=0xc00005adc8 sp=0xc00005ad78 pc=0x6d7e10
github.com/katzenpost/katzenpost/doubleratchet.pairedRatchet(0xb518a8?)
	/build/katzenpost/doubleratchet/ratchet_test.go:25 +0x45 fp=0xc00005ae58 sp=0xc00005adc8 pc=0x6dbc65
github.com/katzenpost/katzenpost/doubleratchet.Test_serialize_savedkeys(0x0?)
	/build/katzenpost/doubleratchet/ratchet_test.go:305 +0x2a fp=0xc00005af70 sp=0xc00005ae58 pc=0x6ddd6a
testing.tRunner(0xc0002d4820, 0x983cf0)
	/usr/lib/go/src/testing/testing.go:1595 +0xff fp=0xc00005afc0 sp=0xc00005af70 pc=0x4ec1ff
testing.(*T).Run.func1()
	/usr/lib/go/src/testing/testing.go:1648 +0x25 fp=0xc00005afe0 sp=0xc00005afc0 pc=0x4ed185
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00005afe8 sp=0xc00005afe0 pc=0x46f261
created by testing.(*T).Run in goroutine 1
	/usr/lib/go/src/testing/testing.go:1648 +0x3ad

goroutine 1 [chan receive]:
runtime.gopark(0x34af11ff2e3b7?, 0x40f985?, 0x48?, 0x0?, 0x18?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000163980 sp=0xc000163960 pc=0x43cf6e
runtime.chanrecv(0xc0002ea000, 0xc000163a67, 0x1)
	/usr/lib/go/src/runtime/chan.go:583 +0x3cd fp=0xc0001639f8 sp=0xc000163980 pc=0x40904d
runtime.chanrecv1(0xbec920?, 0x8e3a60?)
	/usr/lib/go/src/runtime/chan.go:442 +0x12 fp=0xc000163a20 sp=0xc0001639f8 pc=0x408c72
testing.(*T).Run(0xc000105040, {0x95750d?, 0x4ebf3c?}, 0x983cf0)
	/usr/lib/go/src/testing/testing.go:1649 +0x3c8 fp=0xc000163ae0 sp=0xc000163a20 pc=0x4ed028
testing.runTests.func1(0xbeda20?)
	/usr/lib/go/src/testing/testing.go:2054 +0x3e fp=0xc000163b30 sp=0xc000163ae0 pc=0x4ef13e
testing.tRunner(0xc000105040, 0xc000187c48)
	/usr/lib/go/src/testing/testing.go:1595 +0xff fp=0xc000163b80 sp=0xc000163b30 pc=0x4ec1ff
testing.runTests(0xc0001a4140?, {0xbb4560, 0xb, 0xb}, {0x415c5f?, 0xc000187d08?, 0xbed060?})
	/usr/lib/go/src/testing/testing.go:2052 +0x445 fp=0xc000163c78 sp=0xc000163b80 pc=0x4ef025
testing.(*M).Run(0xc0001a4140)
	/usr/lib/go/src/testing/testing.go:1925 +0x636 fp=0xc000163ec0 sp=0xc000163c78 pc=0x4eda16
main.main()
	_testmain.go:67 +0x19c fp=0xc000163f40 sp=0xc000163ec0 pc=0x6ded3c
runtime.main()
	/usr/lib/go/src/runtime/proc.go:267 +0x2bb fp=0xc000163fe0 sp=0xc000163f40 pc=0x43cafb
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000163fe8 sp=0xc000163fe0 pc=0x46f261

goroutine 2 [force gc (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000044fa8 sp=0xc000044f88 pc=0x43cf6e
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:404
runtime.forcegchelper()
	/usr/lib/go/src/runtime/proc.go:322 +0xb3 fp=0xc000044fe0 sp=0xc000044fa8 pc=0x43cdd3
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000044fe8 sp=0xc000044fe0 pc=0x46f261
created by runtime.init.6 in goroutine 1
	/usr/lib/go/src/runtime/proc.go:310 +0x1a

goroutine 18 [GC sweep wait]:
runtime.gopark(0x1?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000040778 sp=0xc000040758 pc=0x43cf6e
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:404
runtime.bgsweep(0x0?)
	/usr/lib/go/src/runtime/mgcsweep.go:321 +0xdf fp=0xc0000407c8 sp=0xc000040778 pc=0x42743f
runtime.gcenable.func1()
	/usr/lib/go/src/runtime/mgc.go:200 +0x25 fp=0xc0000407e0 sp=0xc0000407c8 pc=0x41c5a5
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000407e8 sp=0xc0000407e0 pc=0x46f261
created by runtime.gcenable in goroutine 1
	/usr/lib/go/src/runtime/mgc.go:200 +0x66

goroutine 19 [sleep]:
runtime.gopark(0xc000096000?, 0x25ae6c3e3198?, 0x0?, 0x0?, 0x983e28?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000040f30 sp=0xc000040f10 pc=0x43cf6e
runtime.goparkunlock(...)
	/usr/lib/go/src/runtime/proc.go:404
runtime.(*scavengerState).sleep(0xbed0e0, 0x40d7010000000000)
	/usr/lib/go/src/runtime/mgcscavenge.go:504 +0x113 fp=0xc000040fa0 sp=0xc000040f30 pc=0x424e93
runtime.bgscavenge(0x0?)
	/usr/lib/go/src/runtime/mgcscavenge.go:662 +0x74 fp=0xc000040fc8 sp=0xc000040fa0 pc=0x425294
runtime.gcenable.func2()
	/usr/lib/go/src/runtime/mgc.go:201 +0x25 fp=0xc000040fe0 sp=0xc000040fc8 pc=0x41c545
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000040fe8 sp=0xc000040fe0 pc=0x46f261
created by runtime.gcenable in goroutine 1
	/usr/lib/go/src/runtime/mgc.go:201 +0xa5

goroutine 34 [finalizer wait]:
runtime.gopark(0x198?, 0x94d3e0?, 0x1?, 0xe1?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000044620 sp=0xc000044600 pc=0x43cf6e
runtime.runfinq()
	/usr/lib/go/src/runtime/mfinal.go:193 +0x107 fp=0xc0000447e0 sp=0xc000044620 pc=0x41b5c7
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000447e8 sp=0xc0000447e0 pc=0x46f261
created by runtime.createfing in goroutine 1
	/usr/lib/go/src/runtime/mfinal.go:163 +0x3d

goroutine 35 [IO wait]:
runtime.gopark(0x47e030?, 0xc00009ec30?, 0x80?, 0xec?, 0x49a35d?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc00009ec10 sp=0xc00009ebf0 pc=0x43cf6e
runtime.netpollblock(0x46d2d2?, 0x4061e6?, 0x0?)
	/usr/lib/go/src/runtime/netpoll.go:564 +0xf7 fp=0xc00009ec48 sp=0xc00009ec10 pc=0x435737
internal/poll.runtime_pollWait(0x7f201d05bd40, 0x72)
	/usr/lib/go/src/runtime/netpoll.go:343 +0x85 fp=0xc00009ec68 sp=0xc00009ec48 pc=0x469ca5
internal/poll.(*pollDesc).wait(0xc0000ee100?, 0x4?, 0x0)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:84 +0x27 fp=0xc00009ec90 sp=0xc00009ec68 pc=0x497c47
internal/poll.(*pollDesc).waitRead(...)
	/usr/lib/go/src/internal/poll/fd_poll_runtime.go:89
internal/poll.(*FD).Accept(0xc0000ee100)
	/usr/lib/go/src/internal/poll/fd_unix.go:611 +0x2ac fp=0xc00009ed38 sp=0xc00009ec90 pc=0x49930c
net.(*netFD).accept(0xc0000ee100)
	/usr/lib/go/src/net/fd_unix.go:172 +0x29 fp=0xc00009edf0 sp=0xc00009ed38 pc=0x5e9809
net.(*TCPListener).accept(0xc0000a4160)
	/usr/lib/go/src/net/tcpsock_posix.go:152 +0x1e fp=0xc00009ee18 sp=0xc00009edf0 pc=0x5f9b7e
net.(*TCPListener).Accept(0xc0000a4160)
	/usr/lib/go/src/net/tcpsock.go:315 +0x30 fp=0xc00009ee48 sp=0xc00009ee18 pc=0x5f8e90
net/http.(*onceCloseListener).Accept(0xc0001982d0?)
	<autogenerated>:1 +0x24 fp=0xc00009ee60 sp=0xc00009ee48 pc=0x6adea4
net/http.(*Server).Serve(0xc000098000, {0x9ddf00, 0xc0000a4160})
	/usr/lib/go/src/net/http/server.go:3056 +0x364 fp=0xc00009ef90 sp=0xc00009ee60 pc=0x6a3704
net/http.(*Server).ListenAndServe(0xc000098000)
	/usr/lib/go/src/net/http/server.go:2985 +0x71 fp=0xc00009efc0 sp=0xc00009ef90 pc=0x6a3371
net/http.ListenAndServe(...)
	/usr/lib/go/src/net/http/server.go:3239
github.com/katzenpost/katzenpost/doubleratchet.init.0.func1()
	/build/katzenpost/doubleratchet/ratchet_test.go:386 +0x37 fp=0xc00009efe0 sp=0xc00009efc0 pc=0x6deab7
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc00009efe8 sp=0xc00009efe0 pc=0x46f261
created by github.com/katzenpost/katzenpost/doubleratchet.init.0 in goroutine 1
	/build/katzenpost/doubleratchet/ratchet_test.go:385 +0x1a

goroutine 26 [GC worker (idle)]:
runtime.gopark(0xc000092290?, 0xc000105101?, 0x60?, 0x78?, 0xc0001aafb8?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0001aaf50 sp=0xc0001aaf30 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0001aafe0 sp=0xc0001aaf50 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0001aafe8 sp=0xc0001aafe0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 7 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000045f50 sp=0xc000045f30 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc000045fe0 sp=0xc000045f50 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000045fe8 sp=0xc000045fe0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 25 [GC worker (idle)]:
runtime.gopark(0xc0001aa760?, 0xc000082ea0?, 0xb0?, 0xa7?, 0x4ec1ff?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0001aa750 sp=0xc0001aa730 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0001aa7e0 sp=0xc0001aa750 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0001aa7e8 sp=0xc0001aa7e0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 8 [GC worker (idle)]:
runtime.gopark(0xc0002ac010?, 0xc000007301?, 0x20?, 0x68?, 0xc0000457b8?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000045750 sp=0xc000045730 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000457e0 sp=0xc000045750 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000457e8 sp=0xc0000457e0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 9 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000046750 sp=0xc000046730 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000467e0 sp=0xc000046750 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000467e8 sp=0xc0000467e0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 10 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000046f50 sp=0xc000046f30 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc000046fe0 sp=0xc000046f50 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000046fe8 sp=0xc000046fe0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 11 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000047750 sp=0xc000047730 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000477e0 sp=0xc000047750 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000477e8 sp=0xc0000477e0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000047f50 sp=0xc000047f30 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc000047fe0 sp=0xc000047f50 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000047fe8 sp=0xc000047fe0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 27 [GC worker (idle)]:
runtime.gopark(0x0?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000041750 sp=0xc000041730 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0000417e0 sp=0xc000041750 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0000417e8 sp=0xc0000417e0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 28 [GC worker (idle)]:
runtime.gopark(0x25a7e5686377?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc000041f50 sp=0xc000041f30 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc000041fe0 sp=0xc000041f50 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc000041fe8 sp=0xc000041fe0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 13 [GC worker (idle)]:
runtime.gopark(0x25ae30994702?, 0x0?, 0x0?, 0x0?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0001a6750 sp=0xc0001a6730 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0001a67e0 sp=0xc0001a6750 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0001a67e8 sp=0xc0001a67e0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

goroutine 14 [GC worker (idle)]:
runtime.gopark(0xc1da80?, 0x1?, 0xd1?, 0xe9?, 0x0?)
	/usr/lib/go/src/runtime/proc.go:398 +0xce fp=0xc0001a6f50 sp=0xc0001a6f30 pc=0x43cf6e
runtime.gcBgMarkWorker()
	/usr/lib/go/src/runtime/mgc.go:1295 +0xe5 fp=0xc0001a6fe0 sp=0xc0001a6f50 pc=0x41e125
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:1650 +0x1 fp=0xc0001a6fe8 sp=0xc0001a6fe0 pc=0x46f261
created by runtime.gcBgMarkStartWorkers in goroutine 40
	/usr/lib/go/src/runtime/mgc.go:1219 +0x1c

rax    0xffffffffffffffff
rbx    0x80c2d5786266ee8a
rcx    0xc99bded6e480fbb2
rdx    0xa5a041e8130882d5
rdi    0x6f24902687f0054e
rsi    0xd1fd636a495e3ea5
rbp    0x1780c1e5fa953ab9
rsp    0x7f201ce418f0
r8     0x37f14bda97e7343a
r9     0x514fde6ba7afcbeb
r10    0xfa5f83c94608cf8f
r11    0x7f201ce4e3a0
r12    0xffffffffffffffff
r13    0xde09fc1e3f4365e5
r14    0x75a85f4c6321b2aa
r15    0x1
rip    0x6f43d5
rflags 0x10282
cs     0x33
fs     0x0
gs     0x0
FAIL	github.com/katzenpost/katzenpost/doubleratchet	90.649s
FAIL
```

**Comment by david415** [comment]
this is fixed by the way...works perfectly
