### ISSUE TITLE
upgrade test failure

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/katzenpost#655]
git checkout catshadow_upgrade_test
cd catshadow
make upgrade_test_use_saved
```
... snip ...
gs=docker_test -race -v -timeout 0 -failfast -run UpgradeResume'
=== RUN   TestUpgradeResume_1
=== PAUSE TestUpgradeResume_1
=== RUN   TestUpgradeResume_2
=== PAUSE TestUpgradeResume_2
=== CONT  TestUpgradeResume_2
=== CONT  TestUpgradeResume_1
09:08:08.843 NOTI katzenpost/client: 😼 Katzenpost is still pre-alpha.  DO NOT DEPEND ON IT FOR STRONG SECURITY OR ANONYMITY. 😼
--- FAIL: TestUpgradeResume_1 (0.16s)
panic: RecvRatchetPublic is all zeros [recovered]
	panic: RecvRatchetPublic is all zeros

goroutine 7 [running]:
testing.tRunner.func1.2({0xfdc460, 0x11e01f0})
	/usr/local/go/src/testing/testing.go:1631 +0x3f7
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x6b6
panic({0xfdc460?, 0x11e01f0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/katzenpost/katzenpost/doubleratchet.(*state).Upgrade(0xc0001721a0, 0x15ec720)
	/go/katzenpost/doubleratchet/ratchet.go:207 +0x10ab
github.com/katzenpost/katzenpost/doubleratchet.NewRatchetFromBytes({0x11e2700, 0xc00005e510}, {0xc000412000, 0x2fd, 0x2fd}, {0x11ec160, 0x15ec720})
	/go/katzenpost/doubleratchet/ratchet.go:353 +0x259
github.com/katzenpost/katzenpost/catshadow.(*Contact).UnmarshalBinary(0xc00040e000, {0xc000410000, 0x45b, 0x45b})
	/go/katzenpost/catshadow/contact.go:218 +0x34b
github.com/fxamacker/cbor/v2.fillByteString(0x40, {0xc000410000, 0x45b, 0x45b}, {0x10a29a0?, 0xc00040e000?, 0x47c279?})
	/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.5.0/decode.go:2064 +0x84e
github.com/fxamacker/cbor/v2.(*decoder).parseToValue(0xc00040dcc0, {0x103bc60?, 0xc00011e018?, 0x0?}, 0xc00007eff0)
	/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.5.0/decode.go:898 +0x1405
github.com/fxamacker/cbor/v2.(*decoder).parseArrayToSlice(0xc00041dcc0, {0xfd3420?, 0xc000116008?, 0x0?}, 0xc00007efa0)
	/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.5.0/decode.go:1336 +0x4d3
github.com/fxamacker/cbor/v2.(*decoder).parseToValue(0xc00040dcc0, {0xfd3420?, 0xc000116008?, 0x1?}, 0xc00007efa0)
	/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.5.0/decode.go:982 +0x195d
github.com/fxamacker/cbor/v2.(*decoder).parseMapToStruct(0xc00041dcc0, {0x106db80?, 0xc000116000?, 0x1?}, 0xc00007ef00)
	/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.5.0/decode.go:1814 +0x1685
github.com/fxamacker/cbor/v2.(*decoder).parseToValue(0xc000257cc0, {0xfc7460?, 0xc00011e010?, 0x2c?}, 0xc00007ef00)
	/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.5.0/decode.go:992 +0x168a
github.com/fxamacker/cbor/v2.(*decoder).value(0xc000257cc0, {0xfd3320, 0xc00011e010})
	/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.5.0/decode.go:713 +0x367
github.com/fxamacker/cbor/v2.(*decMode).UnmarshalFirst(0xc000284780, {0xc000402600, 0x585, 0x585}, {0xfd3320, 0xc00011e010})
	/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.5.0/decode.go:647 +0xcd
github.com/fxamacker/cbor/v2.UnmarshalFirst(...)
	/go/pkg/mod/github.com/fxamacker/cbor/v2@v2.5.0/decode.go:114
github.com/katzenpost/katzenpost/catshadow.decryptStateFile({0xc00021a080, 0x3a}, 0xc00009e0c0)
	/go/katzenpost/catshadow/disk.go:124 +0x21c
github.com/katzenpost/katzenpost/catshadow.reloadCatshadowState(0xc00019d520, {0xc00021a080, 0x3a})
	/go/katzenpost/catshadow/client_docker_test.go:99 +0xc8
github.com/katzenpost/katzenpost/catshadow.TestUpgradeResume_1(0xc00019d520)
	/go/katzenpost/catshadow/client_docker_upgrade_test.go:136 +0x11c
testing.tRunner(0xc00019d520, 0x10fabc0)
	/usr/local/go/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x826
exit status 2
FAIL	github.com/katzenpost/katzenpost/catshadow	0.218s
```

**Comment by mixmasala** [comment]
here is a json formatted view of the ratchet state, first, a ratchet state that decoded successfully
```
=== RUN   Test_NewRatchetFromBytes
{
  "SavedKeys": null,
  "RootKey": "G/EodqOS+DeWiEZWK1G+gmoVpDa5iVRM4RPE+Xr1JEQ=",
  "SendHeaderKey": "ONS0Eg4cWU8XPYKtMoOeFAb3xfVFb2cqq4d1QgfULgE=",
  "RecvHeaderKey": "V2f2N7euPnCFwAm1e+SdleAJ+CJvUBbi1+qBMi0DqcU=",
  "NextSendHeaderKey": "Gy9YgY+fWbTOGMwKqQPge10M02chpBK53Ap/OFuZ9cQ=",
  "NextRecvHeaderKey": "ONS0Eg4cWU8XPYKtMoOeFAb3xfVFb2cqq4d1QgfULgE=",
  "SendChainKey": "31/g4WkKK8vG8l7ZiXffVtLRWpaBtg2FjDy43cz4cRM=",
  "RecvChainKey": "XxlQeWTuwwJ2Ph/faxLU+FKbTDvoScRU/FBCl3O/WNA=",
  "SendRatchetPrivate": "mabG0oAsx2POkSDQDo8NNWwMPPI+6TtwjS99Buszxk8=",
  "RecvRatchetPublic": "sJPPmLOSTaAL8nf7spZTjdhJW8AzqDtv9HrjgzsaYzI=",
  "SendPQRatchetPrivate": "NUDhsU8w8y3E70BOtAz/PjzRy0D+Nc1VVCIitcQg7+JFAkzUBA==",
  "RecvPQRatchetPublic": "VmuknmTwZsT0q96pGsmMRLFKkPzprRVZUzdELeakOM7JNKc0OCl4TAv2AxzSxGjHsXFC0Asf0Wt/U/m5v7ZUDw==",
  "SendCount": 2,
  "RecvCount": 1,
  "PrevSendCount": 0,
  "Private0": null,
  "Private1": null,
  "PQPrivate0": "slIA1CVLUlLsIUvC6+HBwc4u5BUhLsTCyw8gHwE98i8TMdDzNA==",
  "PQPrivate1": "VD+7O+Q/LwPT303OzE47LEEl4lEN9S7O0Fy9UhIsAzww8lHe4A==",
  "Ratchet": false
}
```
the ratchet state that causes a crash has 0 filled fields
  "RecvHeaderKey" "RecvChainKey" "RecvRatchetPublic" "RecvPQRatchetPublic"

possibly it is a corrupted ratchet? why would it be in this state?
```
{
  "SavedKeys": null,
  "RootKey": "UV4wwZtj2Ty5Em+sv1u394g1yktYZN31zRh74wAeHkI=",
  "SendHeaderKey": "8vdbE9CWu8K7w6FDoAUCv+11UHuxfn8ZRiOXu13gstc=",
  "RecvHeaderKey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
  "NextSendHeaderKey": "tNqA0lFVtWBeOVkFy5siOoKzvMOa8kT2ycy4d4KFPsg=",
  "NextRecvHeaderKey": "tNqA0lFVtWBeOVkFy5siOoKzvMOa8kT2ycy4d4KFPsg=",
  "SendChainKey": "DCYNW0oiRIUWROQ/dE1H3epETkGQQG1XBOuXTj11pVA=",
  "RecvChainKey": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
  "SendRatchetPrivate": "qXO/xIdN9EL3KtPxSjwLuPuIWvBpHyuv54zKJVSVpjI=",
  "RecvRatchetPublic": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
  "SendPQRatchetPrivate": "BPECRLI9LutMwsTCsbFO07BE5Fzs8lEC3DJS0Rxe3cMg/zDFXw==",
  "RecvPQRatchetPublic": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA==",
  "SendCount": 1,
  "RecvCount": 0,
  "PrevSendCount": 0,
  "Private0": null,
  "Private1": null,
  "PQPrivate0": "/8IuCw/j0O3j1bMiL9LE2/tSDeJAK+PC07E7BLMwvDO7IbHt8g==",
  "PQPrivate1": "BPECRLI9LutMwsTCsbFO07BE5Fzs8lEC3DJS0Rxe3cMg/zDFXw==",
  "Ratchet": false
}
--- FAIL: Test_NewRatchetFromBytes (0.00s)
panic: RecvRatchetPublic is all zeros [recovered]
	panic: RecvRatchetPublic is all zeros

goroutine 19 [running]:
testing.tRunner.func1.2({0x812960, 0x8cf7e0})
	/usr/local/go/src/testing/testing.go:1631 +0x24a
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x377
panic({0x812960?, 0x8cf7e0?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/katzenpost/katzenpost/doubleratchet.(*state).Upgrade(0xc0000dfd40, 0xa324e0)
	/go/katzenpost/doubleratchet/ratchet.go:214 +0x7de
github.com/katzenpost/katzenpost/doubleratchet.NewRatchetFromBytes({0x8d1120, 0xc0000be0c0}, {0xc0001a4600, 0x2fd, 0x600}, {0x8d3b80, 0xa324e0})
	/go/katzenpost/doubleratchet/ratchet.go:364 +0x259
github.com/katzenpost/katzenpost/doubleratchet.Test_NewRatchetFromBytes(0xc0000df520)
	/go/katzenpost/doubleratchet/ratchet_test.go:455 +0x195
testing.tRunner(0xc0000df520, 0x88faa0)
	/usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x390
FAIL	github.com/katzenpost/katzenpost/doubleratchet	0.005s
FAIL
```
