### ISSUE TITLE
client2 "make dockerdockertest" segfault

### ISSUE THREAD

**Issue by mixmasala** [katzenpost/katzenpost#683]
while investigating issue #671:

```
dad86c1c789e:/build/katzenpost/client2# git stash
Saved working directory and index state WIP on (no branch): 69548b87 docker/makefile: use tuning params from main
dad86c1c789e:/build/katzenpost/client2# make dockerdockertest 
podman run --user 0:0 -v /build/katzenpost:/go/katzenpost --network=host --rm -v /build/katzenpost/docker/cache/go:/go/ -v /build/katzenpost/docker/cache/root_cache:/root/.cache katzenpost-alpine_base \
	sh -c 'cd /go/katzenpost/client2/; GORACE=history_size=7 go test  -ldflags "-X github.com/katzenpost/katzenpost/core/epochtime.WarpedEpoch=true" -tags=docker_test -race -v -timeout 1h -run TestAllClient2Tests'
=== RUN   TestAllClient2Tests
09:54:03.726 DEBU katzenpost/client2: Start daemon
09:54:03.729 INFO katzenpost/client2: Katzenpost is still pre-alpha.  DO NOT DEPEND ON IT FOR STRONG SECURITY OR ANONYMITY.
09:54:03.729 DEBU client2/conn: newConnection
09:54:03.729 DEBU client2/listener: Listener worker begin
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x611d42]

goroutine 12 [running]:
net.(*TCPListener).Addr(0x0)
	/usr/local/go/src/net/tcpsock.go:349 +0x22
github.com/katzenpost/katzenpost/client2.(*listener).worker(0xc0000003c0)
	/go/katzenpost/client2/listener.go:79 +0xa9
github.com/katzenpost/katzenpost/core/worker.(*Worker).Go.func1()
	/go/katzenpost/core/worker/worker.go:39 +0x87
created by github.com/katzenpost/katzenpost/core/worker.(*Worker).Go in goroutine 6
	/go/katzenpost/core/worker/worker.go:37 +0x125
exit status 2
FAIL	github.com/katzenpost/katzenpost/client2	0.051s
make: *** [Makefile:26: dockerdockertest] Error 1
```

**Comment by mixmasala** [comment]
```
--- FAIL: TestAllClient2Tests (0.02s)
panic: listen tcp 127.0.0.1:64331: bind: address already in use [recovered]
	panic: listen tcp 127.0.0.1:64331: bind: address already in use

goroutine 7 [running]:
testing.tRunner.func1.2({0xd4d940, 0xc000025590})
	/usr/local/go/src/testing/testing.go:1631 +0x3f7
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1634 +0x6b6
panic({0xd4d940?, 0xc000025590?})
	/usr/local/go/src/runtime/panic.go:770 +0x132
github.com/katzenpost/katzenpost/client2.NewListener(0xc000248240, 0xc000253490?, 0xc00003ac00, 0xc000253490)
	/go/katzenpost/client2/listener.go:263 +0x94d
github.com/katzenpost/katzenpost/client2.(*Daemon).Start(0xc0000dd040)
	/go/katzenpost/client2/daemon.go:148 +0x43b
github.com/katzenpost/katzenpost/client2.setupDaemon()
	/go/katzenpost/client2/client_docker_test.go:56 +0x58
github.com/katzenpost/katzenpost/client2.TestAllClient2Tests(0xc0000ad520)
	/go/katzenpost/client2/client_docker_test.go:28 +0x2a
testing.tRunner(0xc0000ad520, 0xde7b70)
	/usr/local/go/src/testing/testing.go:1689 +0x21f
created by testing.(*T).Run in goroutine 1
	/usr/local/go/src/testing/testing.go:1742 +0x826
exit status 2
FAIL	github.com/katzenpost/katzenpost/client2	0.048s
make: *** [Makefile:26: dockerdockertest] Error 1
dad86c1c789e:/build/katzenpost/client2# grep 64331 *
dad86c1c789e:/build/katzenpost/client2# grep 64331 -r
^C
dad86c1c789e:/build/katzenpost/client2# grep 64331 -r .
./testdata/client.toml:ListenAddress = "localhost:64331"
```

a hung client2.test process was already bound; and the error returned from net.ListenTCP wasn't caught

**Comment by david415** [comment]
i think these bugs have now been fixed and merged
