### ISSUE TITLE
intermittent client2 test failure

### ISSUE THREAD

**Issue by david415** [katzenpost/katzenpost#765]
=== RUN   TestClientPKIStartStop
05:57:10.060 DEBU client2/pki: start
05:57:10.060 DEBU client2/pki: worker
05:57:10.060 DEBU client2/pki: getDocument
05:57:10.060 DEBU client2/pki: Fetching PKI doc for epoch 194201 from Provider.
05:57:10.060 DEBU client2/pki: Terminating gracefully.
05:57:10.061 DEBU client2/pki: Halting PKI worker.
05:57:10.061 DEBU client2/pki: stopping worker
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x103222a78]

goroutine 55 [running]:
github.com/katzenpost/katzenpost/client2.(*pki).getDocument(0xc00023e1e0, {0x103515f38, 0xc000204550}, 0x2f699)
	/Users/runner/work/katzenpost/katzenpost/client2/pki.go:269 +0x6a8
github.com/katzenpost/katzenpost/client2.(*pki).updateDocument(0xc00023e1e0, 0x2f699)
	/Users/runner/work/katzenpost/katzenpost/client2/pki.go:221 +0x1b0
github.com/katzenpost/katzenpost/client2.(*pki).worker(0xc00023e1e0)
	/Users/runner/work/katzenpost/katzenpost/client2/pki.go:177 +0xa94
github.com/katzenpost/katzenpost/core/worker.(*Worker).Go.func1()
	/Users/runner/work/katzenpost/katzenpost/core/worker/worker.go:39 +0x84
created by github.com/katzenpost/katzenpost/core/worker.(*Worker).Go in goroutine 54
	/Users/runner/work/katzenpost/katzenpost/core/worker/worker.go:37 +0x10c
FAIL	github.com/katzenpost/katzenpost/client2	14.225s
	github.com/katzenpost/katzenpost/client2/cmd/kpclientd		coverage: 0.0% of statements
	github.com/katzenpost/katzenpost/client2/common		coverage: 0.0% of statements
# github.com/katzenpost/katzenpost/client2/config.test
ld: warning: '/private/var/folders/t_/mmhnh941511_hp2lwh383bp00000gn/T/go-link-2025285714/000128.o' has malformed LC_DYSYMTAB, expected 98 undefined symbols to start at index 1626, found 95 undefined symbols starting at index 1626
	github.com/katzenpost/katzenpost/client2/internal/proxy		coverage: 0.0% of statements
# github.com/katzenpost/katzenpost/client2/thin.test
ld: warning: '/private/var/folders/t_/mmhnh941511_hp2lwh383bp00000gn/T/go-link-954813014/000128.o' has malformed LC_DYSYMTAB, expected 98 undefined symbols to start at index 1626, found 95 undefined symbols starting at index 1626

**Comment by mixmasala** [comment]
is this testing on alpine? this is likely due to a stack size limitation when using highctidh
