### ISSUE TITLE
malformed mix public key crashes authority

### ISSUE THREAD

**Issue by ioerror** [katzenpost/katzenpost#80]
```
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: 14:28:14.026 NOTI authority: Katzenpost is still pre-alpha.  DO NOT DEPEND ON IT FOR STRONG SECURITY OR ANONYMITY.
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: 14:28:14.067 NOTI authority: Authority identity public key hash is: fc546db935f4250ad478937e553e74bc18b187189d6d72c77a013db2325ed9c9
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: 14:28:14.067 NOTI authority: Authority link public key is: ecd357d36de87670e73cce6807d8d1f80ea89c6e007f785f53ea63b6eda3dd29bc8c247747972df49612c361fc55c2c>
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: 14:28:14.106 NOTI authority: Starting graceful shutdown.
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: 14:28:14.106 NOTI authority: Shutdown complete.
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: panic: failed to decode PEM data from ED25519 SPHINCS+ PUBLIC KEY PEM
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: goroutine 1 [running]:
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: github.com/katzenpost/katzenpost/authority/voting/server.newState(0xc0003e6320)
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]:         /home/user/katzenpost/authority/voting/server/state.go:1502 +0x1290
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: github.com/katzenpost/katzenpost/authority/voting/server.New(0xc0003ee000)
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]:         /home/user/katzenpost/authority/voting/server/server.go:303 +0x8dc
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]: main.main()
Nov 23 14:28:14 power9 pq-katzenpost-authority[910441]:         /home/user/katzenpost/authority/cmd/voting/main.go:52 +0x270
Nov 23 14:28:14 power9 systemd[1]: pq-katzenpost-authority.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

The malformed key in question:
```
-----BEGIN ED25519 SPHINCS+ PUBLIC KEY-----
ri5TtlqPVfVzhQVbuZIgC7Z7n219hjhBnJLqAcs1B7fTOtPrPCqLgdGMXqJYntP1
cGfaofrV5RH/WP9r9yuZRo07ucPIhh8Pk+WqFbW3CcfJveZwawUOri87vJWK1lkn
-----END ED25519 SPHINCS+ PUBLIC KEY-----
```

**Comment by mixmasala** [comment]
that's a crash at startup because the key couldn't be loaded. Not sure why it isn't valid though. The philosphy here is to crash fast on this sort of error because the software shouldn't proceed with bad keys.
